# Generated by Django 4.2.13 on 2026-04-29 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text="Used in URL filters, e.g. 'sim-cards'", unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji icon', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Service Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='What makes this place useful for international students?')),
                ('address', models.CharField(max_length=300)),
                ('maps_link', models.URLField(blank=True, help_text='Full Google Maps URL for this location')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags: english-friendly, halal, vegetarian, 24-hours', max_length=300)),
                ('university', models.CharField(blank=True, help_text='Leave blank to show for all universities', max_length=200)),
                ('verified', models.BooleanField(default=False, help_text='Verified entries are shown by default; unverified are flagged')),
                ('hours', models.CharField(blank=True, help_text='e.g. Mon-Fri 9am-6pm, Sat 10am-4pm', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='directory.servicecategory')),
            ],
            options={
                'verbose_name_plural': 'Service Entries',
                'ordering': ['-verified', 'name'],
            },
        ),
    ]
