# Generated by Django 4.2.13 on 2026-04-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_keyword', models.CharField(help_text='Single keyword or short phrase to match in user messages', max_length=100, unique=True)),
                ('response_text', models.TextField(help_text='The response sent to the user. Keep under 1000 characters for LINE.')),
                ('active', models.BooleanField(default=True)),
                ('category', models.CharField(blank=True, help_text="Optional grouping: 'government', 'banking', 'housing', etc.", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bot FAQ',
                'verbose_name_plural': 'Bot FAQs',
                'ordering': ['trigger_keyword'],
            },
        ),
    ]
